[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "npm"]

[phases.install]
cmds = [
  "cd backend && composer install --no-dev --optimize-autoloader",
  "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = [
  "cd backend && php artisan config:cache",
  "cd backend && php artisan route:cache",
  "cd backend && php artisan view:cache"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"