[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "cd backend && mkdir -p bootstrap/cache && chmod 755 bootstrap/cache",
  "cd backend && mkdir -p database/sqlite && touch database/sqlite/database.db && chmod 666 database/sqlite/database.db",
  "cd backend && composer install --no-dev --optimize-autoloader",
  "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = [
  "cd backend && php artisan config:cache",
  "cd backend && php artisan migrate --force",
  "cd backend && mkdir -p storage/app/public && mkdir -p storage/framework/cache && mkdir -p storage/framework/sessions && mkdir -p storage/framework/views && mkdir -p storage/logs && chmod -R 775 storage"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_PHP_FPM = "false"
NIXPACKS_NO_DEFAULT_CACHE_DIRS = "true"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"

[healthcheck]
path = "/api/health"